/**
 * THIS FILE IS GENERATED by `gulp env` command from `env.json`
 * Generated on Thu May 04 2017 11:44:48 GMT+0530 (India Standard Time)
 *
 * Make sure the keys in `env.model.ts` exist in `env.json`
 * otherwise it'll throw message like this
 * Property '<missing-key>' is missing in type '{}'
 *
 * Feel free to modify for direct updates in development
 */
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ENV = {};

//# sourceMappingURL=env.js.map
